#!/bin/sh

echo scornaz > build/auteur
rm -rf build/ft_printf.h
rm -rf build/*.c
mkdir -p build/includes
cp -R libft build

hs=`find . -name "*.h" | grep -v libft | grep -v build`
cs=`find . -name "*.c" | grep -v libft | grep -v build | grep -v tests | grep -v main.c`

echo $cs

for h in $hs; do
	echo $h
	cp $h build/includes
done

for c in $cs; do
	echo $c
	cp $c build
done

cat <<end > build/Makefile 
NAME := libftprintf.a
SRCS := $(echo $(basename $cs))
LIBFT_OBJS := \$(addprefix libft/, ft_atoi.o ft_nbrsize.o ft_putchar.o ft_putstr.o ft_strany.o ft_strchr.o ft_strequ.o ft_strlen.o ft_strsub.o ft_isdigit.o ft_issep.o ft_strdup.o)
OBJS := \$(SRCS:.c=.o)
INC := \$(addprefix -I, libft includes)

all: \$(NAME)
	 @make -C libft

\$(NAME): \$(OBJS)
	@ar cr \$(NAME) \$(OBJS) \$(LIBFT_OBJS)
	@ranlib \$(NAME)

%.o : %.c
	@gcc -c -g \$(INC) \$< -o \$@

clean:
	@rm -rf \$(OBJS)

fclean: clean
	@rm -rf \$(NAME)

re: fclean all

end
