#!/bin/sh

rm -rf build/
mkdir build
mkdir build/includes
cp -R libft build
rm -rf build/libft/.git*
echo scornaz > build/auteur

hs=`find . -name "*.h" | grep -v libft | grep -v build`
cs=`find . -name "*.c" | grep -v libft | grep -v build | grep -v tests | grep -v main.c`

echo $cs

for h in $hs; do
#	echo $h
	cp $h build/includes 2> /dev/null
done

for c in $cs; do
#	echo $c
	cp $c build 2> /dev/null
done

cat <<end > build/Makefile 
NAME := libftprintf.a
SRCS := $(echo $(basename $cs))
LIBFT_OBJS := \$(addprefix libft/, ft_atoi.o ft_nbrsize.o print/ft_putchar.o print/ft_putstr.o string/ft_strany.o string/ft_strchr.o string/ft_strequ.o string/ft_strlen.o string/ft_strsub.o print/ft_isdigit.o print/ft_issep.o string/ft_strdup.o unicode/unicode.o mem/ft_bzero.o string/ft_strcmp.o array/array.o mem/ft_memcpy.o ft_abs.o unicode/cpy.o)
OBJS := \$(SRCS:.c=.o)
INC := \$(addprefix -I, libft includes)

all: \$(NAME)

\$(NAME): \$(OBJS)
	 @make -C libft
	 @ar cr \$(NAME) \$(OBJS) \$(LIBFT_OBJS)
	 @ranlib \$(NAME)

%.o : %.c
	@gcc -c -g \$(INC) \$< -o \$@

clean:
	@rm -rf \$(OBJS)

fclean: clean
	@rm -rf \$(NAME)

re: fclean all

end
