#!/bin/bash

values=(20)
width=(4 1 10)
precision=(4 10 1)
#flags
minus=("-" "0")
plus=("+" "0")
space=(' ' "0")
alternate=("#" "0")
zero=("0" "0")
#types
types=(d i o u x ld li lo lu lx lld lli llo llu llx)

for value in ${values[@]}; do
    for w in ${width[@]}; do
	for prec in ${precision[@]}; do
	    for min in ${minus[@]}; do
		for pl in ${plus[@]}; do
		    for zero in ${zero[@]}; do
                        echo $zero
			for alt in ${alternate[@]}; do
				for typ in ${types[@]}; do
				    ./test $value $w $prec $typ $zero $min $pl $sp $alt
			    done
			done
		    done
		done
	    done
	done
    done
done
