#!/bin/bash

values=(20)
width=(1)
precision=(1)
#flags
minus=("-" '')
plus=("+" '')
space=(' ' "")
alternate=("#" "")
zero=("0" "")
#types
types=(d i o u x ld li lo lu lx lld lli llo llu llx)


rm -rf log


for value in ${values[@]}; do
    for w in ${width[@]}; do
	for prec in ${precision[@]}; do
	    for min in ${minus[@]}; do
		for pl in ${plus[@]}; do
		    for zero in ${zero[@]}; do
			for alt in ${alternate[@]}; do
				for typ in ${types[@]}; do
				    ./test $value $w $prec $typ $zero $min $pl $sp $alt
			    done
			done
		    done
		done
	    done
	done
    done
done
