#!/bin/bash

echo `tput setaf 6`all args : $@
echo "%$5""$6""$7""$8""$9""${10}""$2"".$3""$4"

diff <(../create_args $1 $2 $3 $5$6$7$8$9$10 $4) <(printf "%$5""$6""$7""$8""$9""${10}""$2"".$3""$4" $1)

if [ $? == 1 ]
then
	echo `tput setaf 9`KO
else
	echo `tput setaf 2`OK
fi
