#!/bin/bash

echo `tput setaf 6`all args : $@

diff <(../create_args $3 $1 $2 $4$5$6$7$8$9 $10) <(printf "%$5$6$7$8$10$2.$3$4" $1)
if [ $? == 1 ]
then
	echo `tput setaf 9`KO
else
	echo `tput setaf 2`OK
fi
